require 'faker'

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin = User.create(username: 'admin', email: 'admin', password: 'admin', role: 'admin')

users = 25.times.map do
  User.create!( :username  => Faker::Zelda.character,
                :email      => Faker::Internet.email,
                :password   => 'password' )
end

category_1 = Category.create({name: "Politics", description: "Political articles and figures."})

category_2 = Category.create({name: "Music", description: "Musical articles and figures."})

category_3 = Category.create({name: "Arts", description: "Artistic articles and figures."})

category_4 = Category.create({name: "Geography", description: "Geographical articles and figures."})

category_5 = Category.create({name: "Sport", description: "Sports articles and figures."})


article_1 = Article.create(title: "Pablo Picasso", body: "Pablo Picasso (/pɪˈkɑːsoʊ, -ˈkæsoʊ/;[2] Spanish: [ˈpaβlo piˈkaso]; 25 October 1881 – 8 April 1973) was a Spanish painter, sculptor, printmaker, ceramicist, stage designer, poet and playwright who spent most of his adult life in France. Regarded as one of the most influential artists of the 20th century, he is known for co-founding the Cubist movement, the invention of constructed sculpture,[3][4] the co-invention of collage, and for the wide variety of styles that he helped develop and explore. Among his most famous works are the proto-Cubist Les Demoiselles d'Avignon (1907), and Guernica (1937), a dramatic portrayal of the bombing of Guernica by the German and Italian airforces.", summary: "Picasso demonstrated extraordinary artistic talent in his early years, painting in a naturalistic manner through his childhood and adolescence. During the first decade of the 20th century, his style changed as he experimented with different theories, techniques, and ideas. After 1906, the Fauvist work of the slightly older artist Henri Matisse motivated Picasso to explore more radical styles, beginning a fruitful rivalry between the two artists, who subsequently were often paired by critics as the leaders of modern art.[5][6][7][8]", user_id: 1)

article_2 = Article.create(title: "Miles Davis", body: "Born and raised in Illinois, Davis left his studies at The Juilliard School in New York City and made his professional debut as a member of saxophonist Charlie Parker's bebop quintet from 1944 to 1948. Shortly after, he recorded the Birth of the Cool sessions for Capitol Records, which were instrumental to the development of cool jazz. In the early 1950s, Davis recorded some of the earliest hard bop music while on Prestige Records but did so haphazardly due to a heroin addiction. After a widely acclaimed comeback performance at the Newport Jazz Festival in 1955, he signed a long-term contract with Columbia Records and recorded the 1957 album 'Round About Midnight.[2] It was his first work with saxophonist John Coltrane and bassist Paul Chambers, key members of the sextet he led into the early 1960s. During this period, he alternated between orchestral jazz collaborations with arranger Gil Evans, such as the Spanish music-influenced Sketches of Spain (1960), and band recordings, such as Milestones (1958) and Kind of Blue (1959).[3] The latter recording remains one of the most popular jazz albums of all time,[4] having sold over four million copies in the U.S.", summary: "Miles Dewey Davis III (May 26, 1926 – September 28, 1991) was an American jazz trumpeter, bandleader, and composer. He is among the most influential and acclaimed figures in the history of jazz and 20th century music. Davis adopted a variety of musical directions in his five-decade career which kept him at the forefront of a number of major stylistic developments in jazz.[1]", user_id: 2)

article_3 = Article.create(title: "Radiohead", body: "After signing to EMI in 1991, Radiohead released their debut single 'Creep' in 1992. It became a worldwide hit after the release of their debut album, Pablo Honey (1993). Their popularity and critical standing rose in the United Kingdom with the release of their second album, The Bends (1995). Radiohead's third album, OK Computer (1997), propelled them to international fame; noted for its complex production and themes of modern alienation, it is often acclaimed as a landmark record of the 1990s[1] and one of the best albums in popular music.[2][3] The group's next albums Kid A (2000) and Amnesiac (2001), recorded simultaneously, marked a dramatic change in style, incorporating influences from experimental electronic music, 20th-century classical music, krautrock, and jazz. Kid A divided listeners but was named the best album of the decade by Rolling Stone, Pitchfork and the Times.", summary: "Radiohead are an English rock band from Abingdon, Oxfordshire, formed in 1985. The band consists of Thom Yorke (lead vocals, guitar, piano, keyboards), Jonny Greenwood (lead guitar, keyboards, other instruments), Ed O'Brien (guitar, backing vocals), Colin Greenwood (bass), and Phil Selway (drums, percussion, backing vocals). They have worked with producer Nigel Godrich and cover artist Stanley Donwood since 1994.", user_id: 3)

article_4 = Article.create(title: "Louis Armstrong", body: "Coming to prominence in the 1920s as an 'inventive' trumpet and cornet player, Armstrong was a foundational influence in jazz, shifting the focus of the music from collective improvisation to solo performance.[3] With his instantly recognizable gravelly voice, Armstrong was also an influential singer, demonstrating great dexterity as an improviser, bending the lyrics and melody of a song for expressive purposes. He was also very skilled at scat singing.", summary: "Louis Daniel Armstrong (August 4, 1901– July 6, 1971), nicknamed Satchmo,[1] Satch or Pops, was an American trumpeter, composer, singer and occasional actor who was one of the most influential figures in jazz. His career spanned five decades, from the 1920s to the 1960s, and different eras in the history of jazz.[2]", user_id: 4)

article_5 = Article.create(title: "Elliott Smith", body: "After playing in the rock band Heatmiser for several years, Smith began his solo career in 1994, with releases on the independent record labels Cavity Search and Kill Rock Stars (KRS). In 1997, he signed a contract with DreamWorks Records, for which he recorded two albums.[6] Smith rose to mainstream prominence when his song 'Miss Misery'—included in the soundtrack for the film Good Will Hunting (1997)—was nominated for an Oscar in the Best Original Song category in 1998.[7]", summary: "Steven Paul 'Elliott' Smith (August 6, 1969 – October 21, 2003) was an American singer, songwriter, and musician. Smith was born in Omaha, Nebraska, raised primarily in Texas, and lived for much of his life in Portland, Oregon, where he first gained popularity. Smith's primary instrument was the guitar, though he was also proficient with piano, clarinet, bass guitar, drums, and harmonica. Smith had a distinctive vocal style, characterized by his 'whispery, spiderweb-thin delivery',[5] and used multi-tracking to create vocal layers, textures, and harmonies.", user_id: 5)

article_6 = Article.create(title: "Stanley Kubrick", body: "Kubrick was raised in the Bronx, New York City, and attended William Howard Taft High School from 1941 to 1945. Although he only received average grades, Kubrick displayed a keen interest in literature, photography, and film from a young age, and taught himself all aspects of film production and directing after graduating from high school. After working as a photographer for Look magazine in the late 1940s and early 1950s, he began making short films on a shoestring budget, and made his first major Hollywood film, The Killing, for United Artists in 1956. This was followed by two collaborations with Kirk Douglas, the war picture Paths of Glory (1957) and the historical epic Spartacus (1960). His reputation as a filmmaker in Hollywood grew, and he was approached by Marlon Brando to film what would become One-Eyed Jacks (1961), though Brando eventually decided to direct it himself.", summary: "Stanley Kubrick (/ˈkuːbrɪk/; July 26, 1928 – March 7, 1999) was an American film director, screenwriter, producer, cinematographer, editor, and photographer. He is frequently cited as one of the greatest and most influential directors in cinematic history. His films, which are mostly adaptations of novels or short stories, cover a wide range of genres, and are noted for their realism, dark humor, unique cinematography, extensive set designs, and evocative use of music.", user_id: 6)

article_7 = Article.create(title: "Martin Scorsese", body: "Part of the New Hollywood wave of filmmaking, he is widely regarded as one of the most significant and influential filmmakers in cinematic history. In 1990, he founded The Film Foundation, a nonprofit organization dedicated to film preservation, and in 2007 he founded the World Cinema Foundation. He is a recipient of the AFI Life Achievement Award for his contributions to the cinema, and has won an Academy Award, a Palme d'Or, Cannes Film Festival Best Director Award, Silver Lion, Grammy Award, Emmys, Golden Globes, BAFTAs, and DGA Awards.", summary: "Martin Charles Scorsese[1] (/skɔːrˈsɛsi/;[2] Italian: [skorˈseːze];[note 1] born November 17, 1942)[3][4][5][6] is an American director, producer, screenwriter, and film historian, whose career spans more than 50 years. Scorsese's body of work addresses such themes as Sicilian-American identity, Roman Catholic concepts of guilt and redemption,[7] faith,[8] machismo, modern crime, and gang conflict. Many of his films are also known for their depiction of violence and liberal use of profanity.", user_id: 7)

article_8 = Article.create(title: "Haruki Murakami", body: "Murakami's most notable works include A Wild Sheep Chase (1982), Norwegian Wood (1987), The Wind-Up Bird Chronicle (1994–95), Kafka on the Shore (2002), and 1Q84 (2009–10). He has also translated into Japanese English works by writers ranging from Raymond Carver to J. D. Salinger. His fiction, still[4] criticized by Japan's literary establishment as un-Japanese, was influenced by Western writers from Chandler to Vonnegut by way of Brautigan. It is frequently surrealistic and melancholic or fatalistic, marked by a Kafkaesque rendition of the 'recurrent themes of alienation and loneliness'[5] he weaves into his narratives. He is also considered an important figure in postmodern literature. Steven Poole of The Guardian praised Murakami as 'among the world's greatest living novelists' for his works and achievements.[6]", summary: "Haruki Murakami (村上 春樹 Murakami Haruki, born January 12, 1949) is a Japanese writer. His books and stories have been bestsellers in Japan as well as internationally, with his work being translated into 50 languages[1] and selling millions of copies outside his native country.[2][3] The critical acclaim for his fiction and non-fiction has led to numerous awards, in Japan and internationally, including the World Fantasy Award (2006) and the Frank O'Connor International Short Story Award (2006). His oeuvre received, for example, the Franz Kafka Prize (2006) and the Jerusalem Prize (2009).", user_id: 8)

article_9 = Article.create(title: "Michael Fassbender", body: "In 2011, Fassbender debuted as the Marvel Comics antihero Magneto in X-Men: First Class, and went on to share the role with Ian McKellen in X-Men: Days of Future Past (2014), and reprised it again in X-Men: Apocalypse (2016). Also in 2011, Fassbender's performance as a sex addict in Shame earned him the Volpi Cup for Best Actor at the Venice Film Festival and was nominated for Golden Globe and BAFTA Awards. In 2013, his role as slave owner Edwin Epps in the slavery epic 12 Years a Slave was similarly praised, earning him his first Oscar nomination for Best Supporting Actor. In 2013, Fassbender appeared in another Ridley Scott film, The Counselor. In 2015, he portrayed the title role in the Danny Boyle-directed biopic Steve Jobs (2015), and played Macbeth in Justin Kurzel's adaptation of William Shakespeare's play. For the former, he has received Academy Award, BAFTA, Golden Globe and SAG nominations. In 2015, he produced the western Slow West, in which he also starred.", summary: "Michael Fassbender (born 2 April 1977) is an Irish actor. His feature film debut was in the fantasy war epic 300 (2007) as a Spartan warrior; his earlier roles included various stage productions, as well as starring roles on television such as in the HBO miniseries Band of Brothers (2001) and the Sky One fantasy drama Hex (2004–05). He first came to prominence for his role as IRA activist Bobby Sands in Hunger (2008), for which he won a British Independent Film Award. Subsequent roles include in the independent film Fish Tank (2009), as a Royal Marines lieutenant in Inglourious Basterds (2009), as Edward Rochester in the 2011 film adaptation of Jane Eyre, as Carl Jung in A Dangerous Method (2011), as the sentient android David 8 in Prometheus (2012) and its sequel, Alien: Covenant (2017), and in the musical comedy-drama Frank (2014) as an eccentric musician loosely inspired by Frank Sidebottom.", user_id: 9)

article_10 = Article.create(title: "Woody Allen", body: "By the mid-1960s, Allen was writing and directing films, first specializing in slapstick comedies before moving into dramatic material influenced by European art cinema during the 1970s, and alternating between comedies and dramas to the present. He is often identified as part of the New Hollywood wave of filmmakers of the mid-1960s to late 1970s.[6] Allen often stars in his films, typically in the persona he developed as a standup. Some of the best-known of his over 50 films are Annie Hall (1977), Manhattan (1979), Hannah and Her Sisters (1986), and Crimes and Misdemeanors (1989). In 2007 he said Stardust Memories (1980), The Purple Rose of Cairo (1985), and Match Point (2005) were his best films.[7] Critic Roger Ebert described Allen as 'a treasure of the cinema'.[8]", summary: "Heywood 'Woody' Allen[1] (born Allan Stewart Konigsberg; December 1, 1935)[2] is an American filmmaker, writer, actor, comedian, and musician whose career spans more than six decades. He worked as a comedy writer in the 1950s, writing jokes and scripts for television and publishing several books of short humor pieces. In the early 1960s, Allen began performing as a stand-up comedian, emphasizing monologues rather than traditional jokes. As a comedian, he developed the persona of an insecure, intellectual, fretful nebbish, which he maintains is quite different from his real-life personality.[3] In 2004, Comedy Central[4] ranked Allen in fourth place on a list of the 100 greatest stand-up comedians, while a UK survey ranked Allen as the third greatest comedian.[5]", user_id: 10)

article_11 = Article.create(title: "Frank Sinatra", body: "Sinatra left Capitol in 1960 to start his own record label, Reprise Records, and released a string of successful albums. In 1965, he recorded the retrospective September of My Years, starred in the Emmy-winning television special Frank Sinatra: A Man and His Music, and released the tracks 'Strangers in the Night' and 'My Way'. After releasing Sinatra at the Sands, recorded at the Sands Hotel and Casino in Vegas with frequent collaborator Count Basie in early 1966, the following year he recorded one of his most famous collaborations with Tom Jobim, the album Francis Albert Sinatra & Antonio Carlos Jobim. It was followed by 1968's collaboration with Duke Ellington. Sinatra retired for the first time in 1971, but came out of retirement two years later and recorded several albums and resumed performing at Caesars Palace, and reached success in 1980 with 'New York, New York'. Using his Las Vegas shows as a home base, he toured both within the United States and internationally until a short time before his death in 1998.", summary: "Francis Albert Sinatra (/sɪˈnɑːtrə/; Italian: [siˈnaːtra]; December 12, 1915 – May 14, 1998) was an American singer, actor, and producer who was one of the most popular and influential musical artists of the 20th century. He is one of the best-selling music artists of all time, having sold more than 150 million records worldwide.[2] Born in Hoboken, New Jersey, to Italian immigrants, Sinatra began his musical career in the swing era with bandleaders Harry James and Tommy Dorsey. Sinatra found success as a solo artist after he signed with Columbia Records in 1943, becoming the idol of the 'bobby soxers'. He released his debut album, The Voice of Frank Sinatra, in 1946. Sinatra's professional career had stalled by the early 1950s, and he turned to Las Vegas, where he became one of its best known performers as part of the Rat Pack. His career was reborn in 1953 with the success of From Here to Eternity, with his performance subsequently winning an Academy Award and Golden Globe Award for Best Supporting Actor. Sinatra released several critically lauded albums, including In the Wee Small Hours (1955), Songs for Swingin' Lovers! (1956), Come Fly with Me (1958), Only the Lonely (1958) and Nice 'n' Easy (1960).", user_id: 11)

article_12 = Article.create(title: "Michael Jordan", body: "Jordan played three seasons for coach Dean Smith at the University of North Carolina. As a freshman, he was a member of the Tar Heels' national championship team in 1982. Jordan joined the Bulls in 1984 as the third overall draft pick. He quickly emerged as a league star, entertaining crowds with his prolific scoring. His leaping ability, demonstrated by performing slam dunks from the free throw line in slam dunk contests, earned him the nicknames Air Jordan and His Airness. He also gained a reputation for being one of the best defensive players in basketball.[6] In 1991, he won his first NBA championship with the Bulls, and followed that achievement with titles in 1992 and 1993, securing a 'three-peat'. Although Jordan abruptly retired from basketball before the beginning of the 1993–94 NBA season and started a new career playing minor league baseball, he returned to the Bulls in March 1995 and led them to three additional championships in 1996, 1997, and 1998, as well as a then-record 72 regular-season wins in the 1995–96 NBA season. Jordan retired for a second time in January 1999, but returned for two more NBA seasons from 2001 to 2003 as a member of the Wizards.", summary: "Michael Jeffrey Jordan (born February 17, 1963), also known by his initials, MJ,[3] is an American retired professional basketball player, businessman, and principal owner and chairman of the Charlotte Hornets of the National Basketball Association (NBA). Jordan played 15 seasons in the NBA for the Chicago Bulls and Washington Wizards. His biography on the NBA website states: 'By acclamation, Michael Jordan is the greatest basketball player of all time.'[4] Jordan was one of the most effectively marketed athletes of his generation and was considered instrumental in popularizing the NBA around the world in the 1980s and 1990s.[5]", user_id: 12)

article_13 = Article.create(title: "Michael Phelps", body: "Phelps is the long course world record holder in the 100 meter butterfly, 200 meter butterfly, and 400 meter individual medley as well as the former long course world record holder in the 200 meter freestyle and 200 meter individual medley. He has won 82 medals in major international long course competition, of which 65 were gold, 14 silver, and 3 bronze, spanning the Olympics, the World Championships, and the Pan Pacific Championships. Phelps's international titles and record-breaking performances have earned him the World Swimmer of the Year Award eight times and American Swimmer of the Year Award eleven times, as well as the FINA Swimmer of the Year Award in 2012 and 2016. Phelps earned Sports Illustrated magazine's Sportsman of the Year award due to his unprecedented Olympic success in the 2008 Games .", summary: "Michael Fred Phelps II[5] (born June 30, 1985)[6] is an American retired competitive swimmer and the most successful and most decorated Olympian of all time,[7] with a total of 28 medals. Phelps also holds the all-time records for Olympic gold medals (23),[8] Olympic gold medals in individual events (13), and Olympic medals in individual events (16).[9] When he won eight gold medals at the 2008 Beijing Games, Phelps broke fellow American swimmer Mark Spitz's 1972 record of seven first-place finishes at any single Olympic Games. At the 2004 Summer Olympics in Athens, Phelps had already tied the record of eight medals of any color at a single Games by winning six gold and two bronze medals. At the 2012 Summer Olympics in London, Phelps won four gold and two silver medals, and at the 2016 Summer Olympics in Rio de Janeiro, he won five gold medals and one silver. This made him the most successful athlete of the Games for the fourth Olympics in a row.[10][11]", user_id: 13)

article_14 = Article.create(title: "Donald Trump", body: "Trump also started several side ventures and branded various products with his name. He is credited with writing or co-writing several books (including The Art of the Deal), and produced and hosted The Apprentice television series for 12 years. As of 2017, he was the 544th richest person in the world, with an estimated net worth of $3.5 billion.Trump had long expressed interest in politics. He entered the 2016 presidential race as a Republican and defeated sixteen opponents in the primaries. Commentators described his political positions as populist, protectionist, and nationalist. His campaign received extensive free media coverage; many of his public statements were controversial or false. Trump won the general election on November 8, 2016, in a surprise victory against Democratic opponent Hillary Clinton. He became the oldest and wealthiest person ever to assume the presidency, the first without prior military or government service, and the fifth to have won the election despite losing the popular vote. His election and policies have sparked numerous protests.", summary: "Donald John Trump (born June 14, 1946) is the 45th and current President of the United States, in office since January 20, 2017. Before entering politics, he was a businessman and television personality.Trump was born in the New York City borough of Queens. He earned an economics degree from the Wharton School of the University of Pennsylvania. A third-generation businessman, Trump followed in the footsteps of his grandmother Elizabeth and father Fred in running the family real estate company. He served as chairman and president of The Trump Organization from 1971 until his inauguration as president in January 2017, when he delegated company management to his sons Donald Jr. and Eric. Trump's business career primarily focused on building or renovating office towers, hotels, casinos, and golf courses, such as Trump Tower and Trump Taj Mahal.", user_id: 14)

article_15 = Article.create(title: "Barack Obama", body: "During his first two years in office, Obama signed many landmark bills. Main reforms were the Patient Protection and Affordable Care Act (often referred to as 'Obamacare', shortened as the 'Affordable Care Act', or abbreviated as the ACA), the Dodd–Frank Wall Street Reform and Consumer Protection Act, and the Don't Ask, Don't Tell Repeal Act of 2010. The American Recovery and Reinvestment Act of 2009 and Tax Relief, Unemployment Insurance Reauthorization, and Job Creation Act of 2010 served as economic stimulus amidst the Great Recession, but the GOP regained control of the House of Representatives in 2011. After a lengthy debate over the national debt limit, Obama signed the Budget Control and the American Taxpayer Relief Acts. In foreign policy, Obama increased U.S. troop levels in Afghanistan, reduced nuclear weapons with the United States–Russia New START treaty, and ended military involvement in the Iraq War. He ordered military involvement in Libya in opposition to Muammar Gaddafi, and the military operation that resulted in the death of Osama bin Laden.", summary: "Barack Hussein Obama II (US: /bəˈrɑːk huːˈseɪn oʊˈbɑːmə/ (About this sound listen) bə-RAHK hoo-SAYN oh-BAH-mə;[1][2] born August 4, 1961) is an American politician who served as the 44th President of the United States from 2009 to 2017. He is the first African American to have served as president. He previously served in the U.S. Senate representing Illinois from 2005 to 2008 and in the Illinois State Senate from 1997 to 2004.Obama was born in 1961 in Honolulu, Hawaii, two years after the territory was admitted to the Union as the 50th state. Raised largely in Hawaii, Obama also spent one year of his childhood in Washington State and four years in Indonesia. After graduating from Columbia University in 1983, he worked as a community organizer in Chicago. In 1988 Obama enrolled in Harvard Law School, where he was the first black president of the Harvard Law Review. After graduation, he became a civil rights attorney and professor, and taught constitutional law at the University of Chicago Law School from 1992 to 2004. Obama represented the 13th District for three terms in the Illinois Senate from 1997 to 2004, when he ran for the U.S. Senate. Obama received national attention in 2004, with his unexpected March primary win, his well-received July Democratic National Convention keynote address, and his landslide November election to the Senate. In 2008, Obama was nominated for president, a year after his campaign began, and after a close primary campaign against Hillary Clinton. He was elected over Republican John McCain, and was inaugurated on January 20, 2009. Nine months later, Obama was named the 2009 Nobel Peace Prize laureate.", user_id: 15)

article_16 = Article.create(title: "Charles Dickens", body: "Dickens's literary success began with the 1836 serial publication of The Pickwick Papers. Within a few years he had become an international literary celebrity, famous for his humour, satire, and keen observation of character and society. His novels, most published in monthly or weekly instalments, pioneered the serial publication of narrative fiction, which became the dominant Victorian mode for novel publication.[4][5] The instalment format allowed Dickens to evaluate his audience's reaction, and he often modified his plot and character development based on such feedback.[5] For example, when his wife's chiropodist expressed distress at the way Miss Mowcher in David Copperfield seemed to reflect her disabilities, Dickens improved the character with positive features.[6] His plots were carefully constructed, and he often wove elements from topical events into his narratives.[7] Masses of the illiterate poor chipped in ha'pennies to have each new monthly episode read to them, opening up and inspiring a new class of readers.[8]", summary: "Charles John Huffam Dickens (/ˈdɪkɪnz/; 7 February 1812 – 9 June 1870) was an English writer and social critic. He created some of the world's best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.[1] His works enjoyed unprecedented popularity during his lifetime, and by the 20th century critics and scholars had recognised him as a literary genius. His novels and short stories enjoy lasting popularity.[2][3]. Born in Portsmouth, Dickens left school to work in a factory when his father was incarcerated in a debtors' prison. Despite his lack of formal education, he edited a weekly journal for 20 years, wrote 15 novels, five novellas, hundreds of short stories and non-fiction articles, lectured and performed extensively, was an indefatigable letter writer, and campaigned vigorously for children's rights, education, and other social reforms.", user_id: 16)

article_17 = Article.create(title: "Nas", body: "His musical career began in 1991, as a featured artist on Main Source's 'Live at the Barbeque'. His debut album Illmatic (1994) received universal acclaim from both critics and the Hip-Hop community and is frequently ranked as the greatest Hip Hop album of all time.[2][3] Nas's follow-up It Was Written debuted at #1 on the Billboard 200, stayed on top for 4 consecutive weeks, went Double Platinum in 2 months, and made Nas internationally known. From 2001-2005, Nas was involved in a highly publicized feud with Jay-Z. Nas signed to Def Jam in 2006. In 2010, he released Distant Relatives, a collaboration album with Damian Marley, donating all royalties to charities active in Africa. His 11th studio album, Life Is Good (2012) was nominated for Best Rap Album at the 55th Annual Grammy Awards. Nas is often named as one of the greatest hip-hop artists. MTV ranked him at #5 on their list of 'The Greatest MCs of All Time'. In 2012, The Source ranked him #2 on their list of the 'Top 50 Lyricists of All Time'. In 2013, Nas was ranked 4th on MTV's 'Hottest MCs in the Game' list. About.com ranked him first on their list of the '50 Greatest MCs of All Time' in 2014, and a year later, Nas was featured on 'The 10 Best Rappers of All Time' list by Billboard.", summary: "Nasir Bin Olu Dara Jones (/nɑːˈsɪər/; born September 14, 1973), better known by his stage name Nas /ˈnɑːz/, is an American hip hop recording artist, record producer, actor and entrepreneur.[1] The son of Olu Dara, Nas has released eight consecutive platinum and multi-platinum albums and has sold over 25 million records worldwide. He is also an entrepreneur through his own record label; he serves as associate publisher of Mass Appeal magazine and is the owner of a Fila sneaker store. He is currently signed to Mass Appeal.", user_id: 17)

article_18 = Article.create(title: "Erykah Badu", body: "Badu's second studio album, Mama's Gun, was released on October 31, 2000.[4] It spawned three singles: 'Bag Lady', which became her first top 10 single on the Billboard Hot 100 peaking at #6, 'Didn't Cha Know?'' and 'Cleva'. The album was certified Platinum by the RIAA.[3] Badu's third album, Worldwide Underground, was released on September 16, 2003.[5] It generated three singles: 'Love of My Life (An Ode to Hip-Hop)', 'Danger' and 'Back in the Day (Puff)' with 'Love' becoming her second song to reach the top 10 of the Billboard Hot 100, peaking at #9. The album was certified Gold by the RIAA.[3] Badu's fourth album, New Amerykah Part One, was released on February 26, 2008.[6] It spawned two singles: 'Honey' and 'Soldier'. New Amerykah Part Two was released in 2010 and fared well both critically and commercially. It contained the album's lead single 'Window Seat', which led to controversy. Influenced by R&B, 1970s soul, and 1980s hip hop,[1] Badu became associated with the neo soul subgenre in the 1990s along with artists like D'Angelo.[7] Her work has often been compared[8] to jazz great Billie Holiday.[9][10] Early in her career, Badu was recognizable for her eccentric style, which often included wearing very large and colorful headwraps. She was a core member of the Soulquarians. As an actress, she has played a wide range of supporting roles in movies including Blues Brothers 2000, The Cider House Rules and House of D. She also speaks at length in the documentaries Before the Music Dies and The Black Power Mixtapes.", summary: "Erica 'Erykah' Abi Wright (born February 26, 1971),[1] better known as Erykah Badu (/ˈɛrɪkə bɑːˈduː/), is an American singer-songwriter, record producer, disc jockey, activist, and actress. Badu's career began after opening a show for D'Angelo in 1994 in Fort Worth; record label executive Kedar Massenburg was highly impressed with her performance and signed her to Kedar Entertainment.[1] Her first album, Baduizm, was released on February 11, 1997.[2] It spawned three singles: 'On & On', 'Next Lifetime' and 'Otherside of the Game'. The album was certified triple Platinum by the Recording Industry Association of America (RIAA).[3] Badu's first live album, Live, was released on November 18, 1997 and was certified double Platinum by the RIAA.[3] Badu is hailed as the queen of neo soul.", user_id: 18)

article_19 = Article.create(title: "D'Angelo", body: "His debut solo album, Brown Sugar, released in July 1995, received rave reviews and sold over two million copies. Along with artists like Erykah Badu, Lauryn Hill, Maxwell, and collaborator Angie Stone, D'Angelo became part of the Neo soul movement. Following this D'Angelo went on a hiatus before releasing Voodoo in January 2000, which debuted at number one. Its lead single 'Untitled (How Does It Feel),'' was a smash on the R&B charts and won a Grammy for Best Male R&B Vocal; likewise, Voodoo won for Best R&B Album. Following the release of 'Untitled (How Does It Feel),' D'Angelo became more uncomfortable with his growing status as a sex symbol. This was followed by numerous personal struggles including alcoholism, and a fourteen-year musical hiatus. D'Angelo released his third studio album, Black Messiah, in December 2014, although it was originally set for release in 2015; the album was met with critical acclaim and fared well on music charts, peaking at number five on the US Billboard 200.", summary: "Michael Eugene Archer[1][2] (born February 11, 1974), better known by his stage name D'Angelo (pronounced dee-Angelo), is an American singer, songwriter, multi-instrumentalist and record producer. Born in Richmond, Virginia, the son of a Pentecostal minister, he began teaching himself piano as a very young child, and at age 18 he won the amateur talent competition at Harlem's Apollo Theater three weeks in a row. After briefly being a member of a hip-hop group called I.D.U., his first major success came in 1994 as the co-writer and co-producer of 'U Will Know'.", user_id: 19)

article_20 = Article.create(title: "Jessica Chastain", body: "Chastain made her film debut in the drama Jolene (2008), and gained wide recognition in 2011 for starring roles in half a dozen films, including the dramas Take Shelter and The Tree of Life. Her performance as an aspiring socialite in The Help earned her an Academy Award for Best Supporting Actress nomination. In 2012, she won a Golden Globe Award and received an Academy Award for Best Actress nomination for playing a CIA agent in the thriller Zero Dark Thirty. Chastain made her Broadway debut in a revival of The Heiress in the same year. Her highest-grossing releases came with the science-fiction films Interstellar (2014) and The Martian (2015), and she continued to draw praise for her performances in the dramas The Disappearance of Eleanor Rigby (2013), A Most Violent Year (2014), and Miss Sloane (2016). Chastain is the founder of the production company Freckle Films, which was created to promote diversity in film. She is vocal about mental health issues, and gender and racial equality. Time magazine named her one of the 100 most influential people in the world in 2012. She is married to the fashion executive Gian Luca Passi de Preposulo.", summary: "Jessica Chastain[a] (born March 24, 1977) is an American actress and film producer. Born and raised in Sacramento County, California, Chastain developed an interest in acting from a young age. In 1998, she made her professional stage debut as Shakespeare's Juliet. After studying acting at the Juilliard School, she was signed to a talent holding deal with the television producer John Wells. She was a recurring guest star in several television shows, including Law & Order: Trial by Jury. She also took on roles in the stage productions of Anton Chekhov's play The Cherry Orchard in 2004 and Oscar Wilde's tragedy Salome in 2006.", user_id: 20)


articles_categories = 20.times.map { ArticleCategory.create!(article_id: rand(1..20), category_id: rand(1..5))}

Article.last.update_attributes(user_id: admin.id)
